[package]
name = "termon"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows-sys = {version = "0.52.0", features =[
    "Win32",
    "Win32_Foundation",
    "Win32_System",
    "Win32_System_Console"]}
